import type { AssetsManifest } from 'pixi.js';

import { GRASS0, GRASS1, GRASS2, WALL0, WALL1, WATER0 } from './constants';
// by starting with ./ we mean "relative to our index.html"
export const manifest: AssetsManifest = {
  bundles: [
    {
      name: 'bundleName',
      assets: {
        player: './player.png',
        // Custom font for menu
        grandstander: 'https://pixijs.com/assets/webfont-loader/Grandstander-ExtraBold.ttf',
        [GRASS0]: './grass0.png',
        [GRASS1]: './grass1.png',
        [GRASS2]: './grass2.png',
        [WALL0]: './wall0.png',
        [WALL1]: './wall1.png',
        [WATER0]: './water0.png',
      },
    },
    {
      name: 'dungeon',
      assets: {
        // Bricks (for small obstacles)
        dungeonBricks1: './dungeon/bricks_1.png',
        dungeonBricks2: './dungeon/bricks_2.png',
        dungeonBricks3: './dungeon/bricks_3.png',
        dungeonBricks4: './dungeon/bricks_4.png',
        dungeonBricks5: './dungeon/bricks_5.png',
        dungeonBricks6: './dungeon/bricks_6.png',
        dungeonBricks7: './dungeon/bricks_7.png',
        dungeonBricks8: './dungeon/bricks_8.png',
        dungeonBricks9: './dungeon/bricks_9.png',
        dungeonBricks10: './dungeon/bricks_10.png',
        // Decor (for decorations and large obstacles)
        dungeonDecor1: './dungeon/decor_1.png',
        dungeonDecor2: './dungeon/decor_2.png',
        dungeonDecor3: './dungeon/decor_3.png',
        dungeonDecor4: './dungeon/decor_4.png',
        dungeonDecor5: './dungeon/decor_5.png',
        dungeonDecor6: './dungeon/decor_6.png',
        dungeonDecor7: './dungeon/decor_7.png',
        dungeonDecor12: './dungeon/decor_12.png',
        dungeonDecor14: './dungeon/decor_14.png',
        dungeonDecor15: './dungeon/decor_15.png',
        // Stones (for floor variation)
        dungeonStones1: './dungeon/stones_1.png',
        dungeonStones2: './dungeon/stones_2.png',
        dungeonStones3: './dungeon/stones_3.png',
        dungeonStones4: './dungeon/stones_4.png',
        dungeonStones5: './dungeon/stones_5.png',
        // Walls (for room boundaries)
        dungeonWall1: './dungeon/wall_1.png',
        dungeonWall2: './dungeon/wall_2.png',
        dungeonWall3: './dungeon/wall_3.png',
        dungeonWall4: './dungeon/wall_4.png',
        dungeonWall5: './dungeon/wall_5.png',
        dungeonWall6: './dungeon/wall_6.png',
        dungeonWall7: './dungeon/wall_7.png',
        dungeonWall8: './dungeon/wall_8.png',
        dungeonWall9: './dungeon/wall_9.png',
        dungeonWall12: './dungeon/wall_12.png',
        dungeonWall13: './dungeon/wall_13.png',
        // Land (floor)
        dungeonLand: './dungeon/land.png',
        // Items
        trophy: './dungeon/trophy.png',
      },
    },
    {
      name: 'dino',
      assets: {
        dinoDead0: './dino/dead0.png',
        dinoDead1: './dino/dead1.png',
        dinoDead2: './dino/dead2.png',
        dinoDead3: './dino/dead3.png',
        dinoDead4: './dino/dead4.png',
        dinoDead5: './dino/dead5.png',
        dinoDead6: './dino/dead6.png',
        dinoDead7: './dino/dead7.png',
        dinoIdle0: './dino/idle0.png',
        dinoIdle1: './dino/idle1.png',
        dinoIdle2: './dino/idle2.png',
        dinoIdle3: './dino/idle3.png',
        dinoIdle4: './dino/idle4.png',
        dinoIdle5: './dino/idle5.png',
        dinoIdle6: './dino/idle6.png',
        dinoIdle7: './dino/idle7.png',
        dinoIdle8: './dino/idle8.png',
        dinoIdle9: './dino/idle9.png',
        dinoJump0: './dino/jump0.png',
        dinoJump1: './dino/jump1.png',
        dinoJump2: './dino/jump2.png',
        dinoJump3: './dino/jump3.png',
        dinoRun0: './dino/run0.png',
        dinoRun1: './dino/run1.png',
        dinoRun2: './dino/run2.png',
        dinoRun3: './dino/run3.png',
        dinoRun4: './dino/run4.png',
        dinoRun5: './dino/run5.png',
        dinoRun6: './dino/run6.png',
        dinoRun7: './dino/run7.png',
        dinoWalk0: './dino/walk0.png',
        dinoWalk1: './dino/walk1.png',
        dinoWalk2: './dino/walk2.png',
        dinoWalk3: './dino/walk3.png',
        dinoWalk4: './dino/walk4.png',
        dinoWalk5: './dino/walk5.png',
        dinoWalk6: './dino/walk6.png',
        dinoWalk7: './dino/walk7.png',
        dinoWalk8: './dino/walk8.png',
        dinoWalk9: './dino/walk9.png',
        dinoWalk10: './dino/walk10.png',
        dinoWalk11: './dino/walk11.png',
      },
    },
  ],
};
